import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Finnex",
  description: "Generated by create Team 404NOTFOUND",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      publishableKey1 ={process.env.publishableKey }
    >
      <html lang="en">
        <body className={outfit.className}>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
